version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: onevote_postgres
    restart: always
    environment:
      POSTGRES_USER: onevote
      POSTGRES_PASSWORD: onevote
      POSTGRES_DB: voting_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: onevote_redis
    ports:
      - "6379:6379"

  voting:
    build: ./backend/services/voting
    container_name: voting_service
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg2://onevote:onevote@postgres:5432/voting_db

volumes:
  postgres_data:
